### ISSUE TITLE
průvodce: [NAHRAĎTE KRÁTKÝM POPISEM]

### ISSUE THREAD

**Issue by peter-ralbovsky** [martinkunc/go-tour-cz#11]
Misspleing bey->bez

Kontext: https://go-tour-cz.appspot.com/basics/12

Nahoře uveďte titulek a zde poskytněte svůj popis problému, nebo poskytněte zpětnou vazbu. Včetně kódu, pokud je potřeba

**Comment by martinkunc** [comment]
Thank you for reporting the issue !
