### ISSUE TITLE
průvodce: podmínkz -> podmínky

### ISSUE THREAD

**Issue by peter-ralbovsky** [martinkunc/go-tour-cz#12]
Kontext: https://go-tour-cz.appspot.com/flowcontrol/11

Nahoře uveďte titulek a zde poskytněte svůj popis problému, nebo poskytněte zpětnou vazbu. Včetně kódu, pokud je potřeba

podmínkz -> podmínky

**Comment by martinkunc** [comment]
Thank you for creating the issue !
