### ISSUE TITLE
průvodce: [Preklepy]

### ISSUE THREAD

**Issue by ghost** [martinkunc/go-tour-cz#13]
Kontext: https://go-tour-cz.appspot.com/list

"Startovací bod, nauč se všechny základz jazyka"
"Deklarace proměnných, volání funkcí, a všechnz věci které potřebuješ vědět pro postup k dalším lekcím."

Cte to vubec nekdo?
Taktez, pred "ktery/ktera/ktere" se pise carka. Vsude vam to chybi.
Na to, ze je to backovano Googlem, nic moc.

**Comment by martinkunc** [comment]
Hi SmallTarzan, thanks for the awesome report, I will try to fix the problems, but it might take me some time. This is only my personal project, derived from official Go tour.

All mistakes are just mine. All the good credit goes to original authors :)
