### ISSUE TITLE
průvodce: Zla informacia o bitovom posune

### ISSUE THREAD

**Issue by uso5** [martinkunc/go-tour-cz#15]
Kontext: https://go-tour-cz.appspot.com/basics/16

V texte je uvedene zle binarne cislo. Pise sa o tom ze ak bude bitovy posun o 100 tak vznikne cislo 1 nasledovane 100 nulami. To nieje pravda pretoze to bude cislo 2^100 co je uplne ine cislo. Nizsie posielam aj ukazku kde sa to vyskytuje. Vdaka.

`// Vytvoř obrovské číslo posouváním 1 bitu doleva o 100 míst.
  // Jinými slovy,, binární číslo 1, následované 100 nulami.
  Big = 1 << 100`

**Comment by martinkunc** [comment]
Ahoj @uso5, mockrat dekuju za popis chyby.
Mozna to neni uplne jasne popsane a vychazel jsem prilis doslovne z originalu tady: https://tour.golang.org/basics/16

Mas prosim nejaky navrh jak by to mohlo byt popsane lepe ?

**Comment by martinkunc** [comment]
Ahoj @uso5, jeste jednou diky, odstranil jsem carku a pridal exponencialni notaci pro vetsi prehlednost.
