### ISSUE TITLE
průvodce: překlep

### ISSUE THREAD

**Issue by janq0** [martinkunc/go-tour-cz#16]
Kontext: https://go-tour-cz.appspot.com/moretypes/20

Na webu je napsáno

> Mapové literály jsou jako strukturové _literély_, ale klíče jsou povinné.

Správně by to mělo být

> Mapové literály jsou jako strukturové _literály_, ale klíče jsou povinné.

**Comment by martinkunc** [comment]
Ahoj @janq0, diky za issue, melo by to byt opraveno.
