### ISSUE TITLE
Typo ve slově "p59kladu"

### ISSUE THREAD

**Issue by martinmares** [martinkunc/go-tour-cz#4]
Kontext: https://go-tour-cz.appspot.com/methods/8

V kapitole "Výběr hodnotového nebo ukazatelového příjemce" chyba ve slově "p59kladu", má být "příkladu".

**Comment by cznic** [comment]
What about a PR collectively fixing all the typos you've found instead of an issue-per-typo?

**Comment by martinmares** [comment]
Ok.

**Comment by martinkunc** [comment]
Hi, thank you for reporting the issue.
