### ISSUE TITLE
průvodce: Bad LINK on Tree doc

### ISSUE THREAD

**Issue by VojRu** [martinkunc/go-tour-cz#9]
Kontext: https://go-tour-cz.appspot.com/concurrency/8

Link is "thttps://godoc.org/golang.org/x/tour/tree#Tree" instead of "https://godoc.org/golang.org/x/tour/tree#Tree"

PS: CZ tutorial has lot of typos. One read&rewrite coudl fix it easily... Someone rly bodged this tutorial.

**Comment by martinkunc** [comment]
Thank you for filling the issue.
Sorry for the typos, I am slowly working on fixing these and other problems as well in the translation.
